"""
Supervisory Signal Fusion
-------------------------

Combines independent supervisory signals into contextual,
evidence-backed supervisory attention signals.

The underlying signals remain traceable. Fusion does not replace
the original analytical findings.

Version: cyberlens-phase3-signal-fusion-0.1.0
"""

from __future__ import annotations

from collections import defaultdict
from typing import Any, Dict, List


VERSION = "cyberlens-phase3-signal-fusion-0.1.0"


PRIORITY_WEIGHT = {
    "LOW": 1,
    "MEDIUM": 2,
    "HIGH": 3,
}


def _priority_from_score(score: int) -> str:
    """
    Convert the accumulated supervisory score into a priority.
    """

    if score >= 7:
        return "HIGH"

    if score >= 4:
        return "MEDIUM"

    return "LOW"


def _confidence_from_signal_count(signal_count: int) -> str:
    """
    Confidence increases when multiple independent signals
    converge on the same entity.
    """

    if signal_count >= 3:
        return "HIGH"

    if signal_count == 2:
        return "MEDIUM"

    return "LOW"


def _build_reason(signals: List[Dict[str, Any]]) -> str:
    """
    Build an explainable rationale from the contributing signals.
    """

    signal_types = sorted(
        {
            signal.get("signal_type", "UNKNOWN")
            for signal in signals
        }
    )

    priorities = sorted(
        {
            signal.get("priority", "LOW")
            for signal in signals
        }
    )

    return (
        f"{len(signals)} supervisory signal(s) converged for this entity. "
        f"Signal types: {', '.join(signal_types)}. "
        f"Observed priorities: {', '.join(priorities)}."
    )


def build_supervisory_signals(
    signals: List[Dict[str, Any]],
    assessment_id: str = "assessment-unknown",
    version: str = VERSION,
) -> List[Dict[str, Any]]:
    """
    Fuse independent analytical signals by entity.

    Parameters
    ----------
    signals:
        List of standardized signals generated by upstream analytics.

    assessment_id:
        Assessment identifier used for traceability.

    version:
        Fusion engine version.

    Returns
    -------
    List[Dict[str, Any]]
        Contextual supervisory signals.

    Notes
    -----
    - Signals are grouped by entity.
    - Each contributing signal remains preserved.
    - Multiple converging signals increase supervisory priority.
    - Source record IDs are aggregated for traceability.
    """

    grouped: Dict[str, List[Dict[str, Any]]] = defaultdict(list)

    for signal in signals:
        entity_id = signal.get("entity_id")

        if entity_id:
            grouped[entity_id].append(signal)

    fused_signals: List[Dict[str, Any]] = []

    for entity_id, entity_signals in grouped.items():

        # ---------------------------------------------------------
        # Calculate weighted supervisory score.
        # ---------------------------------------------------------
        score = sum(
            PRIORITY_WEIGHT.get(
                signal.get("priority", "LOW"),
                1,
            )
            for signal in entity_signals
        )

        priority = _priority_from_score(score)

        # ---------------------------------------------------------
        # Collect signal types.
        # ---------------------------------------------------------
        signal_types = sorted(
            {
                signal.get("signal_type", "UNKNOWN")
                for signal in entity_signals
            }
        )

        rule_ids = sorted(
            {
                signal.get("rule_id", "UNKNOWN")
                for signal in entity_signals
            }
        )

        # ---------------------------------------------------------
        # Preserve every source record ID.
        # ---------------------------------------------------------
        source_record_ids = sorted(
            {
                record_id
                for signal in entity_signals
                for record_id in signal.get("source_record_ids", [])
                if record_id
            }
        )

        # ---------------------------------------------------------
        # Preserve complete underlying evidence.
        # ---------------------------------------------------------
        supporting_signals = []

        for signal in entity_signals:
            supporting_signals.append(
                {
                    "signal_id": signal.get("signal_id"),
                    "signal_type": signal.get("signal_type"),
                    "rule_id": signal.get("rule_id"),
                    "priority": signal.get("priority"),
                    "reason": signal.get("reason"),
                    "evidence": signal.get("evidence", []),
                    "source_record_ids": signal.get(
                        "source_record_ids",
                        [],
                    ),
                }
            )

        # ---------------------------------------------------------
        # Historical and peer context are preserved.
        # ---------------------------------------------------------
        historical_context = [
            signal.get("historical_context", {})
            for signal in entity_signals
            if signal.get("historical_context")
        ]

        peer_context = [
            signal.get("peer_context", {})
            for signal in entity_signals
            if signal.get("peer_context")
        ]

        # ---------------------------------------------------------
        # Confidence based on convergence.
        # ---------------------------------------------------------
        confidence = _confidence_from_signal_count(
            len(entity_signals)
        )

        fused_signals.append(
            {
                "signal_id": f"SUP-{entity_id}-{assessment_id}",
                "signal_type": "SUPERVISORY_ATTENTION",
                "rule_id": "SUP-FUSION-001",
                "category": "SUPERVISORY_SIGNAL_FUSION",
                "priority": priority,
                "reason": _build_reason(entity_signals),
                "evidence": supporting_signals,
                "source_record_ids": source_record_ids,
                "historical_context": historical_context,
                "peer_context": peer_context,
                "evidence_confidence": confidence,
                "rule_model_version": version,
                "entity_id": entity_id,
                "assessment_id": assessment_id,
                "contributing_signal_count": len(entity_signals),
                "contributing_signal_types": signal_types,
                "contributing_rule_ids": rule_ids,
                "supervisory_score": score,
                "human_review_required": True,
            }
        )

    # Highest supervisory priority first.
    priority_order = {
        "HIGH": 3,
        "MEDIUM": 2,
        "LOW": 1,
    }

    fused_signals.sort(
        key=lambda signal: (
            priority_order.get(signal["priority"], 0),
            signal["supervisory_score"],
        ),
        reverse=True,
    )

    return fused_signals